version: "3"

services:
    db:
      image: postgres
      env_file:
        - ./university_api/.env
      volumes:
        - pgdb_data:/var/lib/postgresql/data
      ports:
        - "5435:5432"
      restart: on-failure

    api:
      build: .
      image: quantumwaffy/university-api:1.0.0
      depends_on:
        - db
      command: >
        bash -c "python manage.py wait_for_db &&
        python3 manage.py migrate &&
        python3 manage.py generate_test_data &&
        python3 manage.py test &&
        python3 manage.py runserver 0.0.0.0:8000
        "
      volumes:
        - .:/usr/src/app
      ports:
        - "8000:8000"

    rabbit:
      image: rabbitmq:3-management-alpine
      env_file:
        - ./university_api/.env
      ports:
        - "5675:5672"
        - "15675:15672"
      restart: on-failure

    celery:
      build: .
      image: quantumwaffy/university-api:1.0.0
      depends_on:
        - api
        - rabbit
        - db
      command: celery -A university_api worker -l info -B
      volumes:
        - .:/usr/src/app
volumes:
  pgdb_data: