# Generated by Django 3.2.9 on 2021-11-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, unique=True, verbose_name='Auditorium number')),
                ('capacity', models.IntegerField(verbose_name='Auditorium capacity')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Lecture name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='LectureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Start lecture')),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='audiences', to='api.auditorium')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='api.group')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lectures', to='api.lecture')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='group',
            field=models.ManyToManyField(through='api.LectureGroup', to='api.Group'),
        ),
    ]
