# Generated by Django 3.2.9 on 2021-11-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211104_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Lecture name'),
        ),
    ]
