# Generated by Django 3.2.9 on 2021-11-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lecture_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturegroup',
            options={'ordering': ['start_datetime']},
        ),
    ]
