# Generated by Django 3.2.9 on 2021-11-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lecturegroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=8, unique=True, verbose_name='Group name'),
        ),
    ]
